### ISSUE TITLE
Splunk Addon in Splunk Enterprise 9.1.1

### ISSUE THREAD

**Issue by stinnux** [The-Shadowserver-Foundation/api_utils#4]
I tried to use the Splunk Addon in Splunk Enterprise 9.1.1, but it didn't work.

I can install the Addon and see it in the list of available Apps, but when I click on it only an empty page is shown.

In the python.log I can see that some CSS and JS files seem to be missing. Should this work without them or is there another prerequisite that I need to install?

`2023-11-16 10:12:40,314 +0100 INFO      error:322 - Masking the original 404 message: 'The path '/en-GB/static/@8524505412195C39C962E7C47F0AABED637E082C090B42BE67AC6A64F0BF7A7B:0/app/shadowserver_reports/js/build/tab_home_page.js' was not foun
d.' with 'Page not found!' for security reasons
2023-11-16 10:12:40,315 +0100 INFO      error:322 - Masking the original 404 message: 'The path '/en-GB/static/@8524505412195C39C962E7C47F0AABED637E082C090B42BE67AC6A64F0BF7A7B:0/app/shadowserver_reports/css/tab_home_page-enterprise.css' was n
ot found.' with 'Page not found!' for security reasons
2023-11-16 10:12:40,316 +0100 INFO      error:322 - Masking the original 404 message: 'The path '/en-GB/static/@8524505412195C39C962E7C47F0AABED637E082C090B42BE67AC6A64F0BF7A7B:0/app/shadowserver_reports/js/build/common.js' was not found.' wit
h 'Page not found!' for security reasons`

**Comment by elsif2** [comment]
The app should be installed in `~splunk/etc/apps/shadowserver_reports`.

I do not have any files named `tab_home_page.js` in my instance.

Here is the list of `common.js` files on my instance:
```
./share/splunk/search_mrsparkle/exposed/build/pages/light/common.js
./share/splunk/search_mrsparkle/exposed/build/pages/enterprise/common.js
./share/splunk/search_mrsparkle/exposed/build/pages/dark/common.js
./etc/apps/splunk_monitoring_console/appserver/static/build/pages/enterprise/common.js
./etc/apps/splunk_monitoring_console/appserver/static/build/pages/lite/common.js
```

**Comment by stinnux** [comment]
I've reinstalled Splunk and now it's working. Probably some issue with my setup. Thanks for checking.
