### ISSUE TITLE
API: reports/stats : report-type discrepencies 

### ISSUE THREAD

**Issue by trolldbois** [The-Shadowserver-Foundation/api_utils#5]
When using the reports/stats endpoint, the report_type field takes value with "-" minus sign between words.
ex: scan-rdp, scan-exchange.

but in the schema and reports types list, the words are separated by underscore "_".
ex: scan_rdp, scan_exchange.

it's pretty confusing. Can you either fix the stats endpoint, or amend the documentation to clarify this issue ?

**Comment by elsif2** [comment]
The API has been updated to favor the underscore format.  Either format may be used in the query.
