### ISSUE TITLE
Removing more .pyc files for Splunk Cloud Upload

### ISSUE THREAD

**Issue by lyonheart14** [The-Shadowserver-Foundation/api_utils#7]
Remove .pyc files in _pycache_ folders so that app can be uploaded to Splunk Cloud instances. Output from Splunk Cloud rejection is attached.
[shadowserver_app_vetting.txt](https://github.com/The-Shadowserver-Foundation/api_utils/files/14087296/shadowserver_app_vetting.txt)

**Comment by elsif2** [comment]
Updated.
