### ISSUE TITLE
API net/asn: Incorrect Content-Type header for JSON responses and undocumented 'ip' property

### ISSUE THREAD

**Issue by barbich** [The-Shadowserver-Foundation/api_utils#8]
Hello,

I'm using your REST API (https://api.shadowserver.org/net/asn) and have encountered a couple of issues:

1. Incorrect Content-Type: JSON responses are being returned with the Content-Type header set to text/html; charset=UTF-8. This causes parsing issues on the client-side. (See details and references from the previous draft)

1. Undocumented 'ip' Property:  The response includes an 'ip' property that is not documented in your API specification. Could you please provide information about the purpose of this property and its expected data type?

**Expected Behaviour:**

REST APIs returning JSON data should use the standard Content-Type: application/json header. This ensures client libraries and tools can correctly interpret the response.

**Steps to Reproduce:**

Make a request to api.shadowserver.org/net/asn (for example: curl -v https://api.shadowserver.org/net/asn?origin=8.8.8.8,8.8.4.4)
Observe the Content-Type header in the response.
For example: 
```bash
bash-3.2$ curl -v https://api.shadowserver.org/net/asn?origin=8.8.8.8,8.8.4.4
*   Trying 66.220.6.202:443...
* Connected to api.shadowserver.org (66.220.6.202) port 443
...
...
* using HTTP/1.x
> GET /net/asn?origin=8.8.8.8,8.8.4.4 HTTP/1.1
> Host: api.shadowserver.org
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=UTF-8
< Content-Length: 151
< Date: Fri, 01 Mar 2024 13:30:59 GMT
<
* Connection #0 to host api.shadowserver.org left intact
[{"prefix":"8.8.8.0/24","asn_name":"Google LLC","asn":15169,"ip":"8.8.8.8"},{"ip":"8.8.4.4","prefix":"8.8.4.0/24","asn_name":"Google LLC","asn":15169}]bash-3.2$

```
**Impact:**

1. The incorrect Content-Type header creates (minior) _difficulties_ in properly consuming the API.

1. The lack of documentation for the 'ip' property makes it _challenging_ to understand its role and how to use it reliably.

**Proposed Solution:**

1. Please update your server-side configuration to return the correct `Content-Type: application/json` header for JSON responses.
2. Document the 'ip' property or update the wiki page (https://github.com/The-Shadowserver-Foundation/api_utils/wiki/API:-ASN-and-Network-Queries)

Thanks

**References:**

RFC 8259 (The Application/JSON Media Type for JavaScript Object Notation (JSON)): https://datatracker.ietf.org/doc/html/rfc8259
Thank you for addressing this issue to improve the usability of your API.

**Comment by elsif2** [comment]
The _Content-Type_ has been updated:

`curl -i 'https://api.shadowserver.org/net/asn?origin=8.8.8.8'
`
```
HTTP/1.1 200 OK
Content-Length: 76
Connection: keep-alive
Content-Type: application/json
Date: Sat, 02 Mar 2024 18:40:08 GMT

[{"ip":"8.8.8.8","asn_name":"Google LLC","prefix":"8.8.8.0/24","asn":15169}]
```

The _ip_ field is the IP address from the request.
