### ISSUE TITLE
Connection timed out - Shadowserver Reports for Elasticsearch

### ISSUE THREAD

**Issue by karnamonkster** [The-Shadowserver-Foundation/api_utils#9]
Hi,
Running an report API using the link [For Elastic](https://github.com/The-Shadowserver-Foundation/api_utils/tree/main/elasticsearch)

- Was successful in some run, but no longer able to run on a daily schedule.
- Error below:
 `ERROR: Download failed: <urlopen error [Errno 110] Connection timed out>`

Is there any rate limiting for fetching the reports ? Please help

**Comment by elsif2** [comment]
There is no rate limiting in place.  What is your source IP address?  What organization are you with?

**Comment by karnamonkster** [comment]
Organisation: Tele2 Sverige AB

**Comment by karnamonkster** [comment]
Ok I figured an issue with the config, needed proxy update to the cron as well :)  Should be working now.
